// <auto-generated />
using System;
using EMROOM_emproj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMROOM_emproj.Migrations
{
    [DbContext(typeof(EMROOM_DbContext))]
    [Migration("20260305091034_EMROOM_Initial_Migration")]
    partial class EMROOM_Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Emergency_Case", b =>
                {
                    b.Property<int>("EMROOM_Case_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMROOM_Case_Id"));

                    b.Property<DateTime>("EMROOM_Arrival_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("EMROOM_Patient_Id")
                        .HasColumnType("int");

                    b.Property<string>("EMROOM_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMROOM_Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EMROOM_Triage_Id")
                        .HasColumnType("int");

                    b.HasKey("EMROOM_Case_Id");

                    b.HasIndex("EMROOM_Patient_Id");

                    b.HasIndex("EMROOM_Triage_Id");

                    b.ToTable("EMROOM_Emergency_Cases");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Patient", b =>
                {
                    b.Property<int>("EMROOM_Patient_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMROOM_Patient_Id"));

                    b.Property<int>("EMROOM_Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("EMROOM_Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMROOM_Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EMROOM_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EMROOM_Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EMROOM_Patient_Id");

                    b.ToTable("EMROOM_Patients");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Symptom", b =>
                {
                    b.Property<int>("EMROOM_Symptom_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMROOM_Symptom_Id"));

                    b.Property<string>("EMROOM_Symptom_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EMROOM_Symptom_Id");

                    b.ToTable("EMROOM_Symptoms");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Treatment", b =>
                {
                    b.Property<int>("EMROOM_Treatment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMROOM_Treatment_Id"));

                    b.Property<int>("EMROOM_Case_Id")
                        .HasColumnType("int");

                    b.Property<string>("EMROOM_Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EMROOM_Physician_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("EMROOM_Treated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMROOM_Treatment_Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EMROOM_Treatment_Id");

                    b.HasIndex("EMROOM_Case_Id")
                        .IsUnique();

                    b.HasIndex("EMROOM_Physician_Id");

                    b.ToTable("EMROOM_Treatments");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Triage_Level", b =>
                {
                    b.Property<int>("EMROOM_Triage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMROOM_Triage_Id"));

                    b.Property<string>("EMROOM_Level_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EMROOM_Priority_Score")
                        .HasColumnType("int");

                    b.HasKey("EMROOM_Triage_Id");

                    b.ToTable("EMROOM_Triage_Levels");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_User", b =>
                {
                    b.Property<int>("EMROOM_User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMROOM_User_Id"));

                    b.Property<string>("EMROOM_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EMROOM_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EMROOM_Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EMROOM_Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EMROOM_User_Id");

                    b.ToTable("EMROOM_Users");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Emergency_Case", b =>
                {
                    b.HasOne("EMROOM_emproj.Models.EMROOM_Patient", "EMROOM_Patient")
                        .WithMany("EMROOM_Emergency_Cases")
                        .HasForeignKey("EMROOM_Patient_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMROOM_emproj.Models.EMROOM_Triage_Level", "EMROOM_Triage_Level")
                        .WithMany("EMROOM_Emergency_Cases")
                        .HasForeignKey("EMROOM_Triage_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EMROOM_Patient");

                    b.Navigation("EMROOM_Triage_Level");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Treatment", b =>
                {
                    b.HasOne("EMROOM_emproj.Models.EMROOM_Emergency_Case", "EMROOM_Emergency_Case")
                        .WithOne("EMROOM_Treatment")
                        .HasForeignKey("EMROOM_emproj.Models.EMROOM_Treatment", "EMROOM_Case_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMROOM_emproj.Models.EMROOM_User", "EMROOM_User")
                        .WithMany("EMROOM_Treatments")
                        .HasForeignKey("EMROOM_Physician_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EMROOM_Emergency_Case");

                    b.Navigation("EMROOM_User");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Emergency_Case", b =>
                {
                    b.Navigation("EMROOM_Treatment");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Patient", b =>
                {
                    b.Navigation("EMROOM_Emergency_Cases");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_Triage_Level", b =>
                {
                    b.Navigation("EMROOM_Emergency_Cases");
                });

            modelBuilder.Entity("EMROOM_emproj.Models.EMROOM_User", b =>
                {
                    b.Navigation("EMROOM_Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
